# This file's format is documented at
# https://forge.rust-lang.org/triagebot/index.html

# Enable issue transfers within the org
[transfer]

# Allow some labels to be applied by anyone
[relabel]
allow-unauthenticated = [
    "A-*",
    "C-*",
    "E-*",
]

# Automatically label pull requests touching defined areas
[autolabel."A-frontend"]
trigger_files = [
    "app/",
    "e2e/",
    "tests/"
    "packages/",
    "public/",
    "package.json",
    "pnpm-lock.yaml",
]

[autolabel."A-backend"]
trigger_files = [
    "src/",
    "crates/"
    "migrations/",
    "src/tools/jsondocck",
    "src/tools/jsondoclint",
    "Cargo.toml",
    "Cargo.lock",
]
